name: Build Kivy App (APK Only)

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

env:
  BUILD_NUMBER: 1
  BUILD_VERSION: 1.0.0
  PYTHON_VERSION: "3.12.2"

jobs:
  build-apk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip python3-setuptools python3-wheel
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Build APK using Buildozer
        run: |
          # تهيئة buildozer إن لم يكن موجودًا
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi
          # بناء التطبيق (debug apk)
          buildozer -v android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk-build
          path: bin/*.apk
          if-no-files-found: warn
